openaiAPIKey=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
model=gpt-4o-mini
temperature=0.2
base-url=https://api.openai.com/v1/chat/completions

spreadsheetId=1YUsPWm3-40e0fc0jybsobL36llH7TOEZkXL3EBaHN3c

iterations=2
passThreshold=0.7